services:
  llamacore:
    container_name: llama-core
    build:
      context: .
      dockerfile: LlamaCore/Dockerfile
    image: ${DOCKER_REGISTRY-}llamacore

  ollama:
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:

